<?php
/*
Plugin Name: Brenta Imprese
Version: 1.0.0
Description:
Author: Net7
Author URI: https://www.netseven.it
Plugin URI: https://www.netseven.it

*/

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists('imprese_post_type') ) {

	// Register Custom Post Type
	function imprese_post_type() {

		$labels = array(
			'name'                  => _x( 'Imprese', 'Post Type General Name', 'brenta' ),
			'singular_name'         => _x( 'Impresa', 'Post Type Singular Name', 'brenta' ),
			'menu_name'             => __( 'Imprese', 'brenta' ),
			'name_admin_bar'        => __( 'Imprese', 'brenta' ),
			'archives'              => __( 'Archivio Imprese', 'brenta' ),
			'attributes'            => __( 'Attributi impresa', 'brenta' ),
			'parent_item_colon'     => __( 'Parent Item:', 'brenta' ),
			'all_items'             => __( 'Tutte le imprese', 'brenta' ),
			'add_new_item'          => __( 'Aggiungi nuova impresa', 'brenta' ),
			'add_new'               => __( 'Aggiungi nuova', 'brenta' ),
			'new_item'              => __( 'Nuova impresa', 'brenta' ),
			'edit_item'             => __( 'Modifica Imprese', 'brenta' ),
			'update_item'           => __( 'Aggiorna Impresa', 'brenta' ),
			'view_item'             => __( 'Vedi Impresa', 'brenta' ),
			'view_items'            => __( 'Vedi Imprese', 'brenta' ),
			'search_items'          => __( 'Cerca Impresa', 'brenta' ),
			'not_found'             => __( 'Non trovata', 'brenta' ),
			'not_found_in_trash'    => __( 'Non trovata nel cestino', 'brenta' ),
			'featured_image'        => __( 'Immagine di copertina', 'brenta' ),
			'set_featured_image'    => __( 'Imposta immagine di copertina', 'brenta' ),
			'remove_featured_image' => __( 'Rimuovi immagine di copertina', 'brenta' ),
			'use_featured_image'    => __( 'Usa come immagine di copertina', 'brenta' ),
			'insert_into_item'      => __( 'Aggiungi dentro impresa', 'brenta' ),
			'uploaded_to_this_item' => __( 'Aggiorna questa impresa', 'brenta' ),
			'items_list'            => __( 'Lista imprese', 'brenta' ),
			'items_list_navigation' => __( 'Navigazione lista imprese', 'brenta' ),
			'filter_items_list'     => __( 'Filtra lista imprese', 'brenta' ),
		);
		$args = array(
			'label'                 => __( 'Impresa', 'brenta' ),
			'description'           => __( 'Post Type Imprese', 'brenta' ),
			'labels'                => $labels,
			'supports'              => array( 'title', 'editor', 'revisions' ),
			'hierarchical'          => false,
			'public'                => true,
			'show_ui'               => true,
			'show_in_menu'          => true,
			'menu_position'         => 5,
			'menu_icon'             => 'dashicons-id-alt',
			'show_in_admin_bar'     => true,
			'show_in_nav_menus'     => true,
			'can_export'            => true,
			'has_archive'           => true,
			'exclude_from_search'   => false,
			'publicly_queryable'    => true,
			'capability_type'       => 'page',
			'show_in_rest'          => true,
		);
		register_post_type( 'imprese', $args );

	}
	add_action( 'init', 'imprese_post_type', 0 );

}

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5a5890680290a',
		'title' => 'Credenziali',
		'fields' => array(
			array(
				'key' => 'field_5a5890700d638',
				'label' => 'Trattamento dati personali ai sensi del DLgs 196/2003',
				'name' => 'trattamento_dati_personali',
				'type' => 'true_false',
				'instructions' => 'Presto il consenso al trattamento dei dati personali, che saranno trattati per la finalità per la quale l\'elenco è stato istituito *',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5a5890970d639',
				'label' => 'Username',
				'name' => 'username',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5890a00d63a',
				'label' => 'Password',
				'name' => 'password',
				'type' => 'password',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a5890b50d63b',
				'label' => 'Ripeti Password',
				'name' => 'ripeti_password',
				'type' => 'password',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'imprese',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5a5883220de1f',
		'title' => 'Dati impresa',
		'fields' => array(
			array(
				'key' => 'field_5a58832d56687',
				'label' => 'Impresa',
				'name' => 'impresa',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a58833556688',
				'label' => 'Partita IVA',
				'name' => 'partita_iva',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a58834156689',
				'label' => 'Indirizzo sede legale',
				'name' => 'indirizzo_sede_legale',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5883505668a',
				'label' => 'Comune',
				'name' => 'comune',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5883585668b',
				'label' => 'Provincia',
				'name' => 'provincia',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a58835e5668c',
				'label' => 'CAP',
				'name' => 'cap',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '15',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5883645668d',
				'label' => 'Inidirizzo sede operativa/amministrativa',
				'name' => 'inidirizzo_sede_operativa',
				'type' => 'text',
				'instructions' => 'Se diversa da quella legale',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a58838f5668e',
				'label' => 'Comune',
				'name' => 'sede_operativa_comune',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5883955668f',
				'label' => 'Provincia',
				'name' => 'sede_operativa_provincia',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a58839a56690',
				'label' => 'CAP',
				'name' => 'sede_operativa_cap',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '15',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5883b056691',
				'label' => 'Telefono',
				'name' => 'telefono',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a5883e456692',
				'label' => 'Fax',
				'name' => 'fax',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5883ee56693',
				'label' => 'Email certificata (PEC)',
				'name' => 'email_certificata_pec',
				'type' => 'email',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a58840056694',
				'label' => 'Email alternativa (non PEC)',
				'name' => 'email_alternativa_non_pec',
				'type' => 'email',
				'instructions' => 'Indirizzo alternativo non-PEC a cui il sistema può inviare le comunicazioni e notifiche.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'imprese',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5a5882d72ed62',
		'title' => 'Dati legali rappresentante impresa',
		'fields' => array(
			array(
				'key' => 'field_5a5882e44a26d',
				'label' => 'Nome',
				'name' => 'nome',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5882ee4a26e',
				'label' => 'Cognome',
				'name' => 'cognome',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a5882f64a26f',
				'label' => 'Codice fiscale',
				'name' => 'codice_fiscale',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '80',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'imprese',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => 'Dati del Legale rappresentante dell\'impresa',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5a5885a30da4e',
		'title' => 'Numero dipendenti',
		'fields' => array(
			array(
				'key' => 'field_5a588706b5572',
				'label' => 'Dirigenti dipendenti a tempo determinato',
				'name' => 'dirigenti_dipendenti_tempo_determinato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a588716b5573',
				'label' => 'Dirigenti dipendenti a tempo indeterminato',
				'name' => 'dirigenti_dipendenti_tempo_indeterminato',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a588d154cd91',
				'label' => 'Dirigenti tecnici a tempo determinato',
				'name' => 'dirigenti_tecnici_tempo_determinato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a588d2a4cd92',
				'label' => 'Dirigenti tecnici a tempo indeterminato',
				'name' => 'dirigenti_tecnici_tempo_indeterminato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a588d7f4cd93',
				'label' => 'Quadri tecnici a tempo determinato',
				'name' => 'quadri_tecnici_tempo_determinato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a588df4f15ef',
				'label' => 'Quadri tecnici a tempo indeterminato',
				'name' => 'quadri_tecnici_tempo_indeterminato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a588e14a62ba',
				'label' => 'Quadri amministrativi a tempo determinato',
				'name' => 'quadri_amministrativi_tempo_determinato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a588e29a62bb',
				'label' => 'Quadri amministrativi a tempo indeterminato',
				'name' => 'quadri_amministrativi_tempo_indeterminato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a588e499df25',
				'label' => 'Impiegati tecnici a tempo determinato',
				'name' => 'impiegati_tecnici_tempo_determinato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5a588e6b9df26',
				'label' => 'Impiegati tecnici a tempo indeterminato',
				'name' => 'impiegati_tecnici_tempo_indeterminato',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a588e86efd34',
				'label' => 'Attesto il possesso dei requisiti di ordine generale di cui all\'art. 38 del D.lgs 163/2006',
				'name' => 'requisiti_dlgs_163_2006',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'imprese',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_categorie_specializzate',
		'title' => 'Categorie specializzate',
		'fields' => array(
			array(
				'key' => 'field_os1',
				'label' => 'OS 1',
				'name' => 'os1',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os1_cat',
				'label' => 'Classifica',
				'name' => 'os1_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os2',
				'label' => 'OS 2',
				'name' => 'os2',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os2_cat',
				'label' => 'Classifica',
				'name' => 'os2_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os2',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os2_a',
				'label' => 'OS 2 A',
				'name' => 'og3',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os2_a_cat',
				'label' => 'Classifica',
				'name' => 'os2_a_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os2_a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os2_b',
				'label' => 'OS 2 B',
				'name' => 'os2_b',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os2_b_cat',
				'label' => 'Classifica',
				'name' => 'os2_b_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os2_b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os3',
				'label' => 'OS 3',
				'name' => 'os3',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os3_cat',
				'label' => 'Classifica',
				'name' => 'os3_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os3',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os4',
				'label' => 'OS 4',
				'name' => 'os4',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os4_cat',
				'label' => 'Classifica',
				'name' => 'os4_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os4',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os5',
				'label' => 'OS 5',
				'name' => 'os5',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os5_cat',
				'label' => 'Classifica',
				'name' => 'os5_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os5',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os6',
				'label' => 'OS 6',
				'name' => 'os6',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os6_cat',
				'label' => 'Classifica',
				'name' => 'os6_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os6',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os7',
				'label' => 'OS 7',
				'name' => 'os7',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os7_cat',
				'label' => 'Classifica',
				'name' => 'os7_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os7',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os8',
				'label' => 'OS 8',
				'name' => 'os8',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os8_cat',
				'label' => 'Classifica',
				'name' => 'os8_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os8',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os9',
				'label' => 'OS 9',
				'name' => 'os9',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os9_cat',
				'label' => 'Classifica',
				'name' => 'os9_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os9',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os10',
				'label' => 'OS 10',
				'name' => 'os10',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os10_cat',
				'label' => 'Classifica',
				'name' => 'os10_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os10',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os11',
				'label' => 'OS 11',
				'name' => 'os11',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os11_cat',
				'label' => 'Classifica',
				'name' => 'os11_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os11',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os12',
				'label' => 'OS 12',
				'name' => 'os12',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os12_cat',
				'label' => 'Classifica',
				'name' => 'os12_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os12',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os12_a',
				'label' => 'OS 12 A',
				'name' => 'os12_a',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os12_a_cat',
				'label' => 'Classifica',
				'name' => 'os12_a_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os12_a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os12_b',
				'label' => 'OS 12 B',
				'name' => 'os12_b',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os12_b_cat',
				'label' => 'Classifica',
				'name' => 'os12_b_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os12_b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os13',
				'label' => 'OS 13',
				'name' => 'os13',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os13_cat',
				'label' => 'Classifica',
				'name' => 'os13_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os13',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os14',
				'label' => 'OS 14',
				'name' => 'os14',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os14_cat',
				'label' => 'Classifica',
				'name' => 'os14_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os14',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os15',
				'label' => 'OS 15',
				'name' => 'os15',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os15_cat',
				'label' => 'Classifica',
				'name' => 'os15_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os15',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os16',
				'label' => 'OS 16',
				'name' => 'os16',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os16_cat',
				'label' => 'Classifica',
				'name' => 'os16_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os16',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os17',
				'label' => 'OS 17',
				'name' => 'os17',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os17_cat',
				'label' => 'Classifica',
				'name' => 'os17_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os17',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os18',
				'label' => 'OS 18',
				'name' => 'os18',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os18_cat',
				'label' => 'Classifica',
				'name' => 'os18_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os18',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os18_a',
				'label' => 'OS 18 A',
				'name' => 'os18',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os18_a_cat',
				'label' => 'Classifica',
				'name' => 'os18_a_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os18_a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os18_b',
				'label' => 'OS 18 B',
				'name' => 'os18_b',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os18_b_cat',
				'label' => 'Classifica',
				'name' => 'os18_b_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os18_b',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os19',
				'label' => 'OS 19',
				'name' => 'os19',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os19_cat',
				'label' => 'Classifica',
				'name' => 'os19_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os19',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os20',
				'label' => 'OS 20',
				'name' => 'os20',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os20_cat',
				'label' => 'Classifica',
				'name' => 'os20_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os20',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os21',
				'label' => 'OS 21',
				'name' => 'os21',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os21_cat',
				'label' => 'Classifica',
				'name' => 'os21_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os21',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os22',
				'label' => 'OS 22',
				'name' => 'os22',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os22_cat',
				'label' => 'Classifica',
				'name' => 'os22_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os22',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os23',
				'label' => 'OS 23',
				'name' => 'os23',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os23_cat',
				'label' => 'Classifica',
				'name' => 'os23_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os23',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os24',
				'label' => 'OS 24',
				'name' => 'os24',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os24_cat',
				'label' => 'Classifica',
				'name' => 'os24_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os24',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os25',
				'label' => 'OS 25',
				'name' => 'os25',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os25_cat',
				'label' => 'Classifica',
				'name' => 'os25_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os25',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os26',
				'label' => 'OS 26',
				'name' => 'os26',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os26_cat',
				'label' => 'Classifica',
				'name' => 'os26_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os26',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os27',
				'label' => 'OS 27',
				'name' => 'os27',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os27_cat',
				'label' => 'Classifica',
				'name' => 'os27_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os27',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os28',
				'label' => 'OS 28',
				'name' => 'os28',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os28_cat',
				'label' => 'Classifica',
				'name' => 'os28_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os28',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os29',
				'label' => 'OS 29',
				'name' => 'os29',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os29_cat',
				'label' => 'Classifica',
				'name' => 'os29_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os29',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os30',
				'label' => 'OS 30',
				'name' => 'os30',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os30_cat',
				'label' => 'Classifica',
				'name' => 'os30_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os30',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os31',
				'label' => 'OS 31',
				'name' => 'os31',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os31_cat',
				'label' => 'Classifica',
				'name' => 'os31_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os31',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os32',
				'label' => 'OS 32',
				'name' => 'os33',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os33_cat',
				'label' => 'Classifica',
				'name' => 'os33_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os33',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os34',
				'label' => 'OS 34',
				'name' => 'os34',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os34_cat',
				'label' => 'Classifica',
				'name' => 'os34_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os34',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_os35',
				'label' => 'OS 35',
				'name' => 'os35',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_os35_cat',
				'label' => 'Classifica',
				'name' => 'os35_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_os35',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),

		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'imprese',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));


	// CATEGORIE SPECIALIZZATE
	acf_add_local_field_group(array(
		'key' => 'group_5a58976a176db',
		'title' => 'Categorie generali',
		'fields' => array(
			array(
				'key' => 'field_5a589788422a5',
				'label' => 'OG 1',
				'name' => 'og1',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5a5897a939177',
				'label' => 'Classifica',
				'name' => 'og1_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5a589788422a5',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og2',
				'label' => 'OG 2',
				'name' => 'og2',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og2_cat',
				'label' => 'Classifica',
				'name' => 'og2_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og2',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og3',
				'label' => 'OG 3',
				'name' => 'og3',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og3_cat',
				'label' => 'Classifica',
				'name' => 'og3_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og3',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og4',
				'label' => 'OG 4',
				'name' => 'og4',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og4_cat',
				'label' => 'Classifica',
				'name' => 'og4_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og4',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og5',
				'label' => 'OG 5',
				'name' => 'og5',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og5_cat',
				'label' => 'Classifica',
				'name' => 'og5_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og5',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og6',
				'label' => 'OG 6',
				'name' => 'og6',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og6_cat',
				'label' => 'Classifica',
				'name' => 'og6_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og6',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og7',
				'label' => 'OG 7',
				'name' => 'og7',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og7_cat',
				'label' => 'Classifica',
				'name' => 'og7_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og7',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og8',
				'label' => 'OG 8',
				'name' => 'og8',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og8_cat',
				'label' => 'Classifica',
				'name' => 'og8_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og8',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og9',
				'label' => 'OG 9',
				'name' => 'og9',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og9_cat',
				'label' => 'Classifica',
				'name' => 'og9_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og9',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og10',
				'label' => 'OG 10',
				'name' => 'og10',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og10_cat',
				'label' => 'Classifica',
				'name' => 'og10_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og10',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og11',
				'label' => 'OG 11',
				'name' => 'og11',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og11_cat',
				'label' => 'Classifica',
				'name' => 'og11_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og11',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og12',
				'label' => 'OG 12',
				'name' => 'og12',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og12_cat',
				'label' => 'Classifica',
				'name' => 'og12_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og12',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_og13',
				'label' => 'OG 13',
				'name' => 'og13',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '10',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_og13_cat',
				'label' => 'Classifica',
				'name' => 'og13_cat',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_og13',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					1 => 'I',
					2 => 'II',
					3 => 'III',
					4 => 'III-bis',
					5 => 'IV',
					6 => 'IV-bis',
					7 => 'V',
					8 => 'VI',
					9 => 'VII',
					10 => 'VIII',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'imprese',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => 'Categorie speciali',
	));

endif;